[package]
name = "test-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
json-patch = "3.0.1"
near-workspaces = "0.21.0"
serde = "1.0.215"
serde_json = "1.0.133"
tokio = "1.41.1"
